// Құжаттағы (экранда, Word/PDF-те) тұрақты белгілер материал тілінде шығады.
// Мұғалімнің интерфейсі өзгермейді — тек оқушыға/тексерушіге баратын құжаттың өзі.

import type { Lang } from "./lang";

const QMZH = {
  kk: {
    docTitle: "Қысқа мерзімді сабақ жоспары",
    section: "Бөлім",
    teacher: "Педагогтің тегі, аты, әкесінің аты (болған жағдайда)",
    date: "Күні",
    grade: (n: string) => `Сынып ${n}`,
    attendance: "Қатысушылар саны ______   Қатыспағандар саны ______",
    topic: "Сабақтың тақырыбы",
    objectives: "Оқу бағдарламасына сәйкес оқыту мақсаттары",
    goals: "Сабақтың мақсаты",
    values: "Құндылықтарды дарыту",
    vocabulary: "Пәндік лексика және терминология",
    term: "Термин",
    definition: "Анықтамасы",
    flow: "Сабақтың барысы",
    stageTime: "Сабақтың кезеңі / Уақыт",
    teacherAction: "Педагогтің әрекеті",
    studentAction: "Оқушының әрекеті",
    assessment: "Бағалау",
    resources: "Ресурстар",
    taskN: (n: number) => `${n}-тапсырма`,
    taskRe: /^\d|тапсырма/i,
    method: "Әдіс",
    level: (l: string) => `${l} деңгей`,
    levelLabel: "Деңгейі",
    time: "Уақыты",
    condition: "Шарты",
    steps: "Орындау қадамдары",
    criteriaTitle: "Бағалау критерийлері мен дескрипторлары",
    criterion: "Бағалау критерийі",
    descriptors: "Дескрипторлар",
    points: "Ұпай",
    differentiation: "Саралау",
    expected: "Күтілетін нәтиже",
    planDiff: "Саралау — оқушыларға қалай көбірек қолдау көрсетуді жоспарлайсыз? Қабілетті оқушыларға қандай міндет қоюды жоспарлайсыз?",
    planAssess: "Бағалау — оқушылардың материалды меңгеру деңгейін қалай тексеруді жоспарлайсыз?",
    planSafety: "Денсаулық және қауіпсіздік техникасының сақталуы",
    reflection: "Рефлексия",
    homework: "Үй тапсырмасы",
    resourcesTitle: "Ресурстар мен сілтемелер",
    resource: "Ресурс",
    resourceLink: "Ресурс (сілтеме)",
    platform: "Түрі / платформа",
    usage: "Қолданылуы",
    file: "KMZH",
  },
  ru: {
    docTitle: "Краткосрочный план урока",
    section: "Раздел",
    teacher: "ФИО педагога",
    date: "Дата",
    grade: (n: string) => `Класс ${n}`,
    attendance: "Количество присутствующих ______   Количество отсутствующих ______",
    topic: "Тема урока",
    objectives: "Цели обучения в соответствии с учебной программой",
    goals: "Цели урока",
    values: "Привитие ценностей",
    vocabulary: "Предметная лексика и терминология",
    term: "Термин",
    definition: "Определение",
    flow: "Ход урока",
    stageTime: "Этап урока / Время",
    teacherAction: "Действия педагога",
    studentAction: "Действия ученика",
    assessment: "Оценивание",
    resources: "Ресурсы",
    taskN: (n: number) => `Задание ${n}`,
    taskRe: /^\d|задани/i,
    method: "Метод",
    level: (l: string) => `Уровень ${l}`,
    levelLabel: "Уровень",
    time: "Время",
    condition: "Условие",
    steps: "Шаги выполнения",
    criteriaTitle: "Критерии оценивания и дескрипторы",
    criterion: "Критерий оценивания",
    descriptors: "Дескрипторы",
    points: "Балл",
    differentiation: "Дифференциация",
    expected: "Ожидаемый результат",
    planDiff: "Дифференциация – каким образом Вы планируете оказать больше поддержки? Какие задачи Вы планируете поставить перед более способными учащимися?",
    planAssess: "Оценивание – как Вы планируете проверить уровень усвоения материала учащимися?",
    planSafety: "Здоровье и соблюдение техники безопасности",
    reflection: "Рефлексия",
    homework: "Домашнее задание",
    resourcesTitle: "Ресурсы и ссылки",
    resource: "Ресурс",
    resourceLink: "Ресурс (ссылка)",
    platform: "Тип / платформа",
    usage: "Применение",
    file: "KSP",
  },
} satisfies Record<Lang, unknown>;

export type QmzhLabels = (typeof QMZH)["kk"];
export const qmzhLabels = (lang: Lang | undefined): QmzhLabels => QMZH[lang === "ru" ? "ru" : "kk"];

const TEST = {
  kk: {
    types: {
      levels: "Деңгейлік тест",
      pisa: "Функционалдық сауаттылық тапсырмалары",
      ubt: "ҰБТ форматындағы тест",
      bzb: "Жиынтық бағалау (БЖБ/ТЖБ)",
      open: "Ашық және шығармашылық тапсырмалар",
    } as Record<string, string>,
    difficulty: "Қиындығы",
    questions: (n: number) => `${n} сұрақ`,
    tasks: (n: number) => `${n} тапсырма`,
    total: "Жалпы балл",
    objective: "Оқу мақсаты",
    levelsLegend: "Деңгейлер: A — білу және түсіну, B — қолдану, C — жоғары деңгей дағдылары",
    studentLine: "Оқушының аты-жөні: ____________________________    Сынып: ______    Күні: __________",
    context: "Жағдаят",
    key: "Жауаптар кілті",
    taskHead: (i: number, title: string, level: string, pts: number) => `${i}-тапсырма. ${title} (${level} деңгей, ${pts} балл)`,
    criteriaTitle: "Бағалау критерийлері мен дескрипторлар",
    criterion: "Бағалау критерийі",
    descriptor: "Дескриптор",
    points: "Балл",
    answers: "Үлгі жауаптар (мұғалімге)",
    file: "Test",
  },
  ru: {
    types: {
      levels: "Разноуровневый тест",
      pisa: "Задания на функциональную грамотность",
      ubt: "Тест в формате ЕНТ",
      bzb: "Суммативное оценивание (СОР/СОЧ)",
      open: "Открытые и творческие задания",
    } as Record<string, string>,
    difficulty: "Сложность",
    questions: (n: number) => `вопросов: ${n}`,
    tasks: (n: number) => `заданий: ${n}`,
    total: "Общий балл",
    objective: "Цель обучения",
    levelsLegend: "Уровни: A — знание и понимание, B — применение, C — навыки высокого порядка",
    studentLine: "ФИО ученика: ____________________________    Класс: ______    Дата: __________",
    context: "Ситуация",
    key: "Ключ ответов",
    taskHead: (i: number, title: string, level: string, pts: number) => `Задание ${i}. ${title} (уровень ${level}, ${pts} б.)`,
    criteriaTitle: "Критерии оценивания и дескрипторы",
    criterion: "Критерий оценивания",
    descriptor: "Дескриптор",
    points: "Балл",
    answers: "Образцы ответов (для учителя)",
    file: "Test",
  },
} satisfies Record<Lang, unknown>;

export type TestLabels = (typeof TEST)["kk"];
export const testLabels = (lang: Lang | undefined): TestLabels => TEST[lang === "ru" ? "ru" : "kk"];

/** Сложность (Жеңіл/Орташа/Қиын) орысша. */
export const difficultyIn = (d: string, lang: Lang | undefined) =>
  lang === "ru" ? ({ Жеңіл: "Лёгкий", Орташа: "Средний", Қиын: "Сложный" } as Record<string, string>)[d] ?? d : d;
